### PR TITLE
bdEagles

### PR DESCRIPTION
**Pull request by zgrose**
Preliminary commit for upcoming release requested by @hongkongwargamer but I see @styson is associated with this file so maybe premature?

I believe I've edited all the correct files to make this auto-download from the board-picker. It is an odd design so I'm not sure if/how the LOS thread should be handled other than to just tell people you can't get much info other than the thread itself.

So just creating the PR for now to collect feedback.

### CODE REVIEW

**Comment by BigAl737** [comment]
This was a special request board for Rick Reinesch. We talked about different formats but he chose this one with all 3 maps on the same board. He's aware that the LOS is a string only and that the hex grid won't report correctly for two of the maps. I thought this board was for playtest only but now that you're making it auto-download compatible, maybe he's released it to the masses. Here's his email if you need to talk with him: ctasl at aol dot com

Anything else you need me to look at?

**Comment by hongkongwargamer** [comment]
Al & Z

I sent you both the “authorisation” from Rick Reinesch and Kermit Scott Mullins separately.

Warm regards,

Jack
“Klotzen, nicht Kleckern!!” - Heinz Guderian
http://www.hongkongwargamer.com
Advanced Squad Leader Central (Discord) https://discord.gg/g2mHncC

**Comment by zgrose** [comment]
Going to merge this so that I can make sure I have all the affected files correct, then going to see about tweaking the hexgrid. Since no one has a scenario for it yet, should be safe. :)

**Comment by derimmer** [comment]
Fixing the hexgrid should not be a a huge problem. You need to add some properties to the BoardMetaData.xml file for the board:

hexHeight = "64.47"
hexWidth = "56.25"
A1CenterX = "22.0"
A1CenterY = "32.25"

The values above are from RBv2. I think the hexHeight and hexWdith are the standard values. If bdEagles uses different size hexes then you will have to adjust those values. For a standard Geo board A1CenterX = 0 and A1CenterY = 32.25. As the names suggest, this tells VASL where to put the centre of hex A1 when it creates the underlying hex grid. It then caculates all of the other hex centre points and vertices from their. In your case, use the location of the A1 hex on the map, not the A0 hex. 

You will have to make another adjustment to deal with the fact that the grid starts at A0 with a half hex. I think one of the Peiper II boards has a similar config. I will take a look and post again.

**Comment by BigAl737** [comment]
Unless you've modified the map graphic, the settings in the metadata for the bdEaglesDare should work. Here's a link:

https://www.dropbox.com/s/cdgkxqdwg5b3tpa/bdEaglesDare?dl=0

**Comment by derimmer** [comment]
OK, i just looked at the whole map. For the love of god! I can see getting the grid to work on map 1. It will carry over to map 2 although the numbering will be wrong. I don't think there is a way to fix that. As for map 3, uh-uh, no way Charlie Brown. 

I can understand why someone would create a paper version of the map this way. For vasl purposes why not create 3 separate maps. FB is done that way.

**Comment by derimmer** [comment]
In Al's map, at least all three maps have the hex grid running in the same direction. His A1CenterX and A1CenterY values look good to me. And you should also add altHexGrain=true to your BoardMetaData.xml file as he has done. If that doesn't work, you can also use the parameter hexgridconfig. See BoardMetaData.java and LOS.Map.map.java for usage. 

I presume that there is some need to see all 3 maps at one and to move units on all of them when playing the scenario.

**Comment by zgrose** [comment]
Heh, ya. I didn't make it, just facilitating the integration into the board picker. Now that all the bits are in the correct place the project principles can decide on tweaks.

**Comment by derimmer** [comment]
Well, the board shows up in the VASL board list and opens. The hexgrid tweaks should allow it to be useable (at present moving units creates a VASSAL error and nothing will move). As for map 3, . . . .

**Comment by BigAl737** [comment]
> I can understand why someone would create a paper version of the map this way. For vasl purposes why not create 3 separate maps. FB is done that way.

The bdEaglesDare with three maps on one page is the way Rick wanted it. It seems this board has morphed past my initial vaslization though. And the parties using this resource seems to have changed. I'm willing to help out if needed but not sure of my place in all this so I'll step aside.

**Comment by derimmer** [comment]
And I certainly don't wish to dictate to the creators what they should do or how they should it. Just trying to make helpful suggestions. It's their map and they should have it as they wish.

**Comment by zgrose** [comment]
@BigAl737 like I said, I'm just facilitating a board getting into the list. We can swap out the contents of that board at any time before there is a published scenario which should be the end of October. Maybe we can setup a Discord/Zoom call with all the principles to hash out the final iteration? I'm happy to host that meeting. I'm sure 15 minutes of video chat will be time well spent for a successful "launch" of this pack.

**Comment by derimmer** [comment]
Happy to be part of a call and available most any time.

**Pull request merged**
