### PR TITLE
Toolbar images are fuzzy in 6.6.0

### LINKED ISSUE #751: Toolbar images are fuzzy in 6.6.0
Toolbar counters and text are not as clear as before and definitely not as clear as counters/text on the map.

### PR DESCRIPTION
**Pull request by uckelman**
Fixes #751. Also cleans up QC.java a little (though much, much more could be done---I suggest looking into the checkstyle plugin that VASSAL has been using since spring).

### CODE REVIEW

**Comment by uckelman** [comment]
These changes require VASSAL 3.4.6 and will crash with anything earlier. I found Bug 13508 in VASSAL while fixing this issue, and the fix for this issue uses the fix 13508 essentially.

**Comment by uckelman** [comment]
The changes which matter for fixing #751 involve `SizedImageIcon` and `MenuSizedImageIcon` at the bottom of `QC.java`. What I've done is routed button icon scaling through our scaler rather than letting Java do the rather poor upscaling that it does on HiDPI screens.

**Comment by derimmer** [comment]
please go ahead with the push. Thanks very much for all this effort.

**Comment by derimmer** [comment]
I have a 6.6.1 build using 3.4.6 and it appears that all the fixes are working. So, again thanks for the help.

I am getting a generic custom code warning whenever I open a game. It is not tied to a specific line of code the way the other ones are. I have built 6.6.1 with the show deprecation line added to the pom and their are about 6 or 8 I need to fix. I can't do all of that before I put 6.6.1 out.  I would like to eliminate this one:

 [Out Of Date Custom Code] This module contains outdated custom code, which is not guaranteed to work with versions of VASSAL released after 2-Oct-2021.
 - [Out Of Date Custom Code] Please check whether there is an updated version of this module. If not, please contact the maintainer of this module and request that it be fixed, or post a message on the Vassal forums and ask for help.

Any idea how to turn this one message off? If not, I will have to live with it.

**Comment by derimmer** [comment]
OK.  I seem to have fixed it myself. More by luck than design. 6.6.1 is ready to go and should issue tonight.

**Comment by uckelman** [comment]
Look in the errorLog. There will be a message there telling you exactly what function was called.

**Comment by uckelman** [comment]
It's likely `VASSAL.Info.getHomeDir`. You should use `getConfDir()` instead.

You can find information about replacements of deprecated functions in VASSAL's Javadoc: http://www.vassalengine.org/javadoc/3.4.6/

**Comment by uckelman** [comment]
Also, you should see these deprecation warnings when you compile:
```
[WARNING] /home/uckelman/projects/VASSAL/VASL/vasl/src/VASL/build/module/map/QC.java:[382,42] getHomeDir() in VASSAL.Info has been deprecated and marked for removal
[WARNING] /home/uckelman/projects/VASSAL/VASL/vasl/src/VASL/build/module/map/QC.java:[927,42] getHomeDir() in VASSAL.Info has been deprecated and marked for removal
```

**Comment by derimmer** [comment]
Yes that was the one. I just happened to pick that one to try while I was waiting to hear back from you. This is all brand new stuff to me!

**Comment by uckelman** [comment]
You guys might want to go through the list of deprecation warnings to clean them up. If you want any advice about how, please ask. We've already gone through most of this ourselves with VASSAL.

**Pull request merged**
