### PR TITLE
Warning cleanup

### PR DESCRIPTION
**Pull request by uckelman**
This PR addresses various compiler warnings.

### CODE REVIEW

**Comment by derimmer** [comment]
I don't know if the first one needs to change or not. I am pretty sure that the second one should NOT change. There was a bug I fixed recently that was mis-reporting ranges when the LOS engine was bounced by an overlay and reverted to the VASSAL los or not. I don't know if it was in this code or elsewhere that I had to make a change. I would have to look at my previous commit and also test this code to be sure.

**Comment by uckelman** [comment]
> Is it correct that only the first LOSMap needs to change in these lines?

Yes. 

`Map.range` is a static member function. You _can_ call static member functions on an instance, but there's no reason to go through the effort of getting an instance when you know what the class is. Calling `sourceLocation.getHex().getMap()` just to get _the class_ is a waste of effort, and obscures what's actually happening.

The _arguments_ to `Map.range` are all instances, so need to remain as they are.

**Comment by uckelman** [comment]
> I am pretty sure that the second one should NOT change. 

Correct. That wouldn't compile due to the types being wrong.

**Comment by zgrose** [comment]
Great, I was just doing an eyeball review. Looks good to merge to me, @derimmer

**Comment by derimmer** [comment]
OK by me.

**Pull request merged**
