### PR TITLE
Feature/david db2

### PR DESCRIPTION
**Pull request by davidsullivan317**

### CODE REVIEW

**Comment by davidsullivan317** [comment]
Initial prototype for #233

**Comment by derimmer** [comment]
All of this reminds me that we should push the new documentation from my DougRTestBranch up to develop as discussed. 

 

Should I do this or is it something you need to manage?

 

Doug

**Comment by davidsullivan317** [comment]
Create a pull request for your branch and I'll merge it in.

**Comment by derimmer** [comment]
Done

**Pull request merged**
