### PR TITLE
#764 Fix Java (*not VASSAL*) deprecated code

### PR DESCRIPTION
**Pull request by mtl1971**
Only the VASSAL deprecated code left:

[WARNING] /D:/dev/vasl/src/VASL/build/module/map/ASLBoardPicker.java:[129,36] dataError(VASSAL.build.BadDataReport) in VASSAL.tools.ErrorDialog has been deprecated
[WARNING] /D:/dev/vasl/src/VASL/build/module/map/ASLBoardPicker.java:[143,32] dataError(VASSAL.build.BadDataReport) in VASSAL.tools.ErrorDialog has been deprecated
[WARNING] /D:/dev/vasl/src/VASL/build/module/map/ASLBoardPicker.java:[605,28] dataError(VASSAL.build.BadDataReport) in VASSAL.tools.ErrorDialog has been deprecated
[WARNING] /D:/dev/vasl/src/VASL/build/module/map/boardPicker/ASLBoard.java:[132,24] dataError(VASSAL.build.BadDataReport) in VASSAL.tools.ErrorDialog has been deprecated
[WARNING] /D:/dev/vasl/src/VASL/build/module/map/boardPicker/Overlay.java:[140,38] getImageInputStream(java.lang.String) in VASSAL.tools.DataArchive has been deprecated and marked for removal
[WARNING] /D:/dev/vasl/src/VASL/build/module/map/boardPicker/Overlay.java:[192,35] getImageSize(java.lang.String) in VASSAL.tools.DataArchive has been deprecated and marked for removal
[WARNING] /D:/dev/vasl/src/VASL/build/module/map/boardPicker/SSROverlay.java:[70,34] getImageInputStream(java.lang.String) in VASSAL.tools.DataArchive has been deprecated and marked for removal
[WARNING] /D:/dev/vasl/src/VASL/build/module/map/boardPicker/Underlay.java:[70,32] getImage(java.lang.String) in VASSAL.tools.DataArchive has been deprecated and marked for removal
[WARNING] /D:/dev/vasl/src/VASL/counters/Turreted.java:[115,19] getCurrentImage() in VASSAL.counters.Embellishment0 has been deprecated and marked for removal

### CODE REVIEW

**Comment by derimmer** [comment]
Great work!

As you can see from other issues (#764 and #748) we, or at least I, need some help from the VASSAL team on the remaining deprecated code almost all of which deals with BoardPicker. There is also one is Turreted. I believe it is one of the decorator classes and to be honest I have been looked at that code for 6 years and still can't figure it out. Not that it is bad code; it is just too complex for me. I get the theory of decorating but not these mechanics. 

Anyway, I have posted an issue on VASSAL and am awaiting help from them.

**Comment by mtl1971** [comment]
NP, Doug. Yes, I saw the discussion, and thought it best to leave the VASSAL part to wiser heads than mine. This PR touches quite a few bits of the codebase; I tested what I could, and it seems to work fine but some I couldn't test - the board archive, for example.

**Comment by mtl1971** [comment]
Happy to help out with the VASSAL deprecated stuff when you feel VASSAL is in a stable enough state to have a go. Let me know what you'd like me to look at.

**Comment by derimmer** [comment]
Look at the thread below and feel free to try any of @uckelman 's suggestions, using VASSAL3.5.0-beta2. 

https://github.com/vasl-developers/vasl/issues/764#issuecomment-764973526

In reference to your previous comments about boardarchive, if you have opened a new game or a saved game then you have used boardarchive.

**Comment by mtl1971** [comment]
Great! BTW, is there a test script, or something I should look at running / doing before creating a PR other than testing locally by hand?

**Comment by derimmer** [comment]
> Great! BTW, is there a test script, or something I should look at running / doing before creating a PR other than testing locally by hand?

No, we have no test scripts that I am aware of.

**Pull request merged**
