### PR TITLE
#474 Update bdBFPB

### PR DESCRIPTION
**Pull request by BigAl737**

### CODE REVIEW

**Comment by BigAl737** [comment]
Doug...yours for updated LOS

**Comment by derimmer** [comment]
Al, when you revised the bdBFPB.gif, did you by any chance make it smaller? It is showing a file size of 1798 x 643 pixels, which is slightly smaller than the standard 1800 x 645 size. This has no impact on the board displaying in VASL but it is playing hell with the LOS engine, which expects centre dots to be in certain places, particularly the half-hex ones at the bottom of the board, such as B10, which should be in row 644 or 645 but there ain't no such rows in a 643 pixel height image. I am pretty sure this is why I can't generate new losdata. Any chance you can have a look and see if you made a change in size?

**Comment by BigAl737** [comment]
Did I make is smaller? Yes I did. Not sure how that happened. There’s some other stuff with BFPB too. Give me a day and I’ll post new files that hopefully will fix everything.

**Comment by BigAl737** [comment]
Try it now...

**Comment by derimmer** [comment]
I have been slow getting to this due to real-life. On it now.

**Pull request merged**
