### PR TITLE
Build with maven-wrapper and pull VASSAL from its maven repo

### PR DESCRIPTION
**Pull request by uckelman**
This PR does two things:

* It switches builds to use maven-wrapper instead of maven directly. Any command you would have run as `mvn` you now run as `./mvnw` instead. (E.g., `./mvnw clean package`.) This should foreclose any difficulties people had getting a functioning Maven setup.

* VASSAL and all its dependencies are now fetched from VASSAL's maven repo. This should make it much easier to keep current with us. (Note that what we have in the repo right now is 3.3.3-alpha1, which is not general release, only a build I've tagged just so we can test the repo. We're aiming to release betas for 3.3.3 in a few days, which will start showing up there as well.)

### CODE REVIEW

**Comment by derimmer** [comment]
Tried this and I think I am totally lost.

I cloned uckelman:maven

As usual, I changed the project structure to add the /lib and vengine.jar to module dependencies

In the pom I changed the vasl build name and updated the argument for VASSAL to 3.3.3-alpha1.jar in the <groupId>org.codehaus.mojo</groupId> item.

I then went to the command line, changed to the project directory and entered mvnw install (all this as normal except for using mvnw instead of mvn).

This is the error message I got:

C:\Users\dougr_000\IdeaProjects\vaslmvnwrapper> mvnw install

Exception calling "DownloadFile" with "2" argument(s): "An exception occurred during a WebClient request."
At line:1 char:282
+ ... pe]::Tls12; $webclient.DownloadFile('https://repo.maven.apache.org/ma ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain
Caused by: java.lang.ClassNotFoundException: org.apache.maven.wrapper.MavenWrapperMain

**Comment by uckelman** [comment]
> As usual, I changed the project structure to add the /lib and vengine.jar to module dependencies

I don't understand what you mean by this. What is the change you're making exactly?

> In the pom I changed the vasl build name and updated the argument for VASSAL to 3.3.3-alpha1.jar in the org.codehaus.mojo item.

I don't follow this either. What exactly is the change?

**Comment by derimmer** [comment]
> > As usual, I changed the project structure to add the /lib and vengine.jar to module dependencies
> 
> I don't understand what you mean by this. What is the change you're making exactly?

In my IDE, under the tab Project Structure-> Modules, I add the Vengine file and the lib directory to the Dependency list. Perhaps this is something that we have to do in JetBrains IDE and would not have to do in say, Eclipse, I don't know. I have done it for every VASL module, I have ever built. 

See the image below, which is actually from a different project, the one I tried to build to test the right-click fix. When I went back to the project which I built to test #723, I could not find the lib directory, which I know I had added before.  So I deleted the project and cloned uckelman:maven again. And again there is no lib directory. There is a mvnw file and a mvnw.cmd file in the top level directory. So, I don't know how I added a lib directory the first time, perhaps I selected the wrong damn project. 

Be that as it may, I tried to build the second clone of uckelman:maven using mvnw install from the command line. Same error message. 

I apologize for the mass confusion in my mind about this. It is clearly stuff that I don't understand. I feel like I am simply guessing what to do, and guessing wrong.

modulessnip
> 
> > In the pom I changed the vasl build name and updated the argument for VASSAL to 3.3.3-alpha1.jar in the org.codehaus.mojo item.
> 
> I don't follow this either. What exactly is the change?


In the pom.xml file, I changed the reference to VASSAL in the section visible in the image below to VASSAL3.3.3-alpha1.jar It was previously VASSAL3.3.2.jar, updated from VASSAL3.2.17 when we built the VASL6.6.0-beta1.vmod just recently.

pomsnip

**Comment by zgrose** [comment]
You don't want VEngine.jar as a module dependency if it is coming down via maven. 
I presume the vassal library in maven also exposes dependencies so the top two lines should be removed but I haven't built to validate that statement (in a middle of another big project).

**Comment by uckelman** [comment]
Hang on a bit. I'm also in the middle of something else atm. I'll try to get back to you as soon as I can.

**Comment by derimmer** [comment]
No rush.

**Comment by uckelman** [comment]
1) I've merged PR #726 into this because it needs a current VASSAL JAR and Maven is the easiest way to get that.

2) I'd missed committing one of the parts of Maven Wrapper in an earlier version of this PR. It's there now. You should be able to build VASL using the following:

Linux:
```
./mvnw clean package
``` 

Windows:
```
mvnw.cmd clean package
```

**Comment by derimmer** [comment]
Build success. 

Now, I need to test it by running it. Which version of VASSAL should I install and use the open the VASL module? And where do I get it.

**Comment by derimmer** [comment]
> You don't want VEngine.jar as a module dependency if it is coming down via maven.
> I presume the vassal library in maven also exposes dependencies so the top two lines should be removed but I haven't built to validate that statement (in a middle of another big project).
Zoltan, I replied to this yesterday but it seems to have gotten lost in transit. In any event, the latest for Joel has eliminated the lib directory so no need/way to do what I was doing before. Not quite sure if the project will run in my IDE. will test that later tonight.

**Comment by uckelman** [comment]
Development snapshots are here: http://www.vassalengine.org/~uckelman/tmp/

The one I uploaded just now is VASSAL-3.3.3-SNAPSHOT-bd388670.

You'll want to update the pom.xml use 3.3.3-beta1 when we release that, which I hope will be in the coming week.

**Comment by derimmer** [comment]
I was able to run the build version with the snapshot you referred to. 

The right-click fix seemed to work fine. Thanks!

@uckelman These changes can be pushed to develop I think.

**Comment by derimmer** [comment]
As per my previous, my built version of VASL is working fine. However, when I try to run the project (that I used to build this latest version of VASL) in my IDE, I get the following error message:

2020-08-09 13:48:52,257 [0-main] INFO  VASSAL.launch.StartUp - Starting
2020-08-09 13:48:52,277 [0-main] INFO  VASSAL.launch.StartUp - OS Windows 10 10.0
2020-08-09 13:48:52,280 [0-main] INFO  VASSAL.launch.StartUp - Java version 11.0.7
2020-08-09 13:48:52,281 [0-main] INFO  VASSAL.launch.StartUp - VASSAL version 3.3.3-alpha2-54f4ca19
2020-08-09 13:48:52,281 [0-main] INFO  VASSAL.launch.Launcher - Player
2020-08-09 13:48:53,782 [0-IconFactory-preload] INFO  VASSAL.tools.icon.IconFactory - VASSAL images folder found at jar:file:/C:/Users/dougr_000/.m2/repository/org/vassalengine/vassal-app/3.3.3-alpha2/vassal-app-3.3.3-alpha2.jar!/images/
2020-08-09 13:48:53,790 [0-IconFactory-preload] ERROR VASSAL.tools.ErrorDialog - 
java.lang.ClassCastException: class sun.net.www.protocol.file.FileURLConnection cannot be cast to class java.net.JarURLConnection (sun.net.www.protocol.file.FileURLConnection and java.net.JarURLConnection are in module java.base of loader 'bootstrap')
	at VASSAL.tools.icon.IconFactory.findJarIcons(IconFactory.java:381)
	at VASSAL.tools.icon.IconFactory.initVassalIconFamilys(IconFactory.java:295)
	at VASSAL.tools.icon.IconFactory$1.run(IconFactory.java:99)
	at java.base/java.lang.Thread.run(Thread.java:834)

Any thoughts?

**Comment by uckelman** [comment]
For clarity, did you still have Vengine.jar set in your IDE as a dependency when that happened?

**Comment by derimmer** [comment]
> For clarity, did you still have Vengine.jar set in your IDE as a dependency when that happened?

No, after cloning the repo, I think the only change I made was to rename the vasl module to be built in the pom file. I left everything else untouched. 

There are about 20+ new module dependencies listed, all beginning with maven and including "maven: org.vassalengine:vassal-app:3.3.3-alpha2." These show up in the External Libraries directory of the project. None of them contain a reference to sun.net . . . 

Thanks for your help on this.

**Comment by uckelman** [comment]
Does C:/Users/dougr_000/.m2/repository/org/vassalengine/vassal-app/3.3.3-alpha2/vassal-app-3.3.3-alpha2.jar exist?

**Comment by derimmer** [comment]
> Does C:/Users/dougr_000/.m2/repository/org/vassalengine/vassal-app/3.3.3-alpha2/vassal-app-3.3.3-alpha2.jar exist?

Yes

**Comment by Stew-rt** [comment]
I can confirm I get the same issue in Intellij if i try to run from the IDE.
This seems to be an import order issue, as I can work around if I change the order of module dependencies in the IDE
under File -> Project Structure -> Modules (Dependencies):

Screenshot from 2020-08-14 09-46-04

Notice `*vassal-app*` is now above `<Module source>`

I'm pretty sure the IDE's Maven integration will monkey with this if it re-imports (I wonder if there's a way to get pom.xml to describe this?)

I can now "Run" from within IDEA, my "Run -> Application" config is as follow (it may be different if you are on a different OS):
Main class: `VASSAL.launch.Player`
VM options: `-Xms256M -Xmx512M -DVASSAL.id=1 -DVASSAL.port=35131 -Duser.home=/home/stewart -Duser.dir=/home/stewart/IdeaProjects/vassal`
Program arguments: `--standalone /home/stewart/testing/vasl/target/vasl-6.6.0-beta1.vmod`
Working directory: `/home/stewart/IdeaProjects/vassal`

**Comment by derimmer** [comment]
This fixed my problem. 

I had to make "Maven:org.vassalengine.vassal-app:3.3.3-alpha2" the very first line of Module/Dependencies. 

This is something we always had to do with the Vengine.jar from the lib folder when building using VASSAL3.2.17.  But since the lib directory is gone in 3.3.3, I did not think to apply it to the vassal-app:3.3.3-alpha2 dependency. 

But we are used to having to do this and can easily include it in our build instructions which need a total rewrite in any event. 

Now I can start on some of the VASSAL errors. NPE errors, in my experience with VASL, are generally easy to fix once we replicate them. It is usually a special circumstance that results in a variable not being created. Finding it can be hard but fixing it is mostly straightforward.

**Comment by derimmer** [comment]
Please go ahead and push these commits to vasl-develop. Thanks for your help on all of this.

**Pull request merged**
