### PR TITLE
Correct board gSK Orchard issue

### PR DESCRIPTION
**Pull request by vidskogs**
Correct board gSK Orchard tree problem

### CODE REVIEW

**Comment by geezer09** [comment]
I think this PR includes some of the same changes as your other #1888. Can you explain why both PRs are needed or remove the other one if it isnt?

**Comment by vidskogs** [comment]
I was trying to make an update to the board but i had trouble  adding new copies of the files with the edit of the version file.ArvidOn Dec 6, 2024, at 8:32 AM, Joseph Larochelle ***@***.***> wrote:﻿
I think this PR includes some of the same changes as your other #1888. Can you explain why both PRs are needed or remove the other one if it isnt?

**Comment by geezer09** [comment]
So I’m still not clear on if two pull requests are required here. It seems like both of them involve modifications to starter kit board g. Can you combine those two into a single pull request or just delete the other one if it is not needed? 

Do you have write access to the repository?

**Comment by zgrose** [comment]
There are a few git beginners here. It's spammy but at least it's 'safe'

**Pull request merged**
