### PR TITLE
#1313 remove color file bd 47 - 76

### PR DESCRIPTION
**Pull request by derimmer**

### CODE REVIEW

**Comment by derimmer** [comment]
Would someone please "review" this pr and approve it so that it can be pushed to develop. I will sort out the bd53 conflict - I have the solution ready to go as soon as this pr is pushed.

Thanks.

**Comment by apbills** [comment]
I think I managed to review this, let me know if it is does not work.

**Review by apbills — COMMENTED** [review]
I think this moves it along.

**Comment by derimmer** [comment]
> I think this moves it along.

@apbills I can see that you have reviewed this but not approved it. I think I need you to approve it.

**Comment by apbills** [comment]
I do not see an "approve" button - just a Close with comment button.  Is that how I approve?

**Comment by derimmer** [comment]
In the top right corner, click on the the "call out" icon on the line with your name under reviewers.

Next window, top right corner again. Click on the green Review Changes button. Then select Approve and the green button below it.

**Review by apbills — APPROVED** [review]

**Comment by derimmer** [comment]
@apbills Many thanks. This did not unlock the gate to my problem. So, I am going to have to go the long way around. But appreciate the help.

**Pull request closed without merging**
