### PR TITLE
Updated VASSAL to 3.4.0

### PR DESCRIPTION
**Pull request by uckelman**
We released 3.4.0-beta1 a few minutes ago. You'll want to update to building against that.

(We're not releasing 3.3.3. Instead, what was going to be 3.3.3 and 3.3.4 will be released as 3.4.0 after this beta.)

### CODE REVIEW

**Comment by uckelman** [comment]
We just released VASSAL 3.4.0. I've adjusted this PR to reflect that.

You should be able to put out a new release compiled against 3.4.0 now.

**Comment by derimmer** [comment]
Go ahead and merge the commits into develop. Thanks.

**Comment by derimmer** [comment]
I have created a build using vassal3.4.0. No problems at first blush. 

I intend to release the official VASL6.6.0 sometime this fall. There are a few VASL bugs that I am trying to get to before release.

**Comment by uckelman** [comment]
If the bugs you're working on are not new bugs, I'd encourage you to cut a release now and work on those bugs for a subsequent release. A new release containing bugs which existed in the previous release makes no one worse off, but would put an end to all the compatibility question we have to field.

**Comment by derimmer** [comment]
Understood. However, the frequency of VASSAL updates is also a factor. 3.4.1 is out already. Do we have to issue a new build of VASL everytime there is a new VASSAL version? If so, then perhaps waiting makes sense. In no sense do I mean this to be criticial of VASSAL. I am well aware that a number of the recent VASSAL versions have been created to specifically address concerns related to VASL. We appreciate the effort and attention that has been put into working with us.  Perhaps we should build on the most recent VASSAL version, put out VASL6.6.0 officially and hold there for a while?

**Comment by uckelman** [comment]
We aim for binary compatibility across releases with the same minor version. Within one minor version, the changes are all bug fixes, not file format or API changes. There should be no difference for compilation of VASL if you compile against 3.4.0 or 3.4.1. We're preparing 3.4.2 now, and that will also be binary-compatible with any other 3.4 release. 

If you build VASL against 3.4.1, you should expect it to work with all 3.4 releases. 

We're _also_ preparing 3.5.0 now---which we don't guarantee will be binary-compatible---but might still be, depending on what changes are in it. Any changes that might require module updates will be in the release notes.

We're expecting to have a release every few weeks for the foreseeable future, so if you're waiting for an extended period where there are no releases, we don't have one planned.

**Comment by derimmer** [comment]
If I want to build against 3.4.2, all I need to do is to make the changes to the pom.xml? There are also references to the vassal version in the buildFile and moduledata and I will update them. 

We don't need to push anything up to github and then clone the reopo? 

I have a change to VASL that I want to put out so I think i will be releasing 6.6.0 officially this week and it might as well be on 3.4.2.

**Comment by derimmer** [comment]
OK, to answer my own question, I just built 6.6.0 against 3.4.2 and it all went well. During the maven build process I could see messages that vassal 3.4.2 was download. So the new mvn tools you gave us are working. Thanks again. 

If the final user test comes back positive I will issue 6.6.0 officially in a few days.

**Pull request merged**
