### PR TITLE
Update boards gSK and hSK with LOS Data

### PR DESCRIPTION
**Pull request by vidskogs**

### CODE REVIEW

**Comment by geezer09** [comment]
Hey @vidskogs, it seems like you changed the name of the board in boards/src/bdgSK/BoardMetadata.xml to "g Starter Kit" and left in unchanged in boards/v5boardVersions.xml to "gSK".

Is that a mistake?

**Comment by vidskogs** [comment]
> Hey @vidskogs, it seems like you changed the name of the board in boards/src/bdgSK/BoardMetadata.xml to "g Starter Kit" and left in unchanged in boards/v5boardVersions.xml to "gSK".
> 
> Is that a mistake?

After reviewing other starter kit boards, for consistency, I will change "g Starter Kit" to "gSK"

**Comment by geezer09** [comment]
Thanks at @vidskogs for your contribution. I assume you don’t have permission to merge the pull request and will go ahead and merge it. Can you please double check after I do merge that everything is working properly?

**Comment by vidskogs** [comment]
> Thanks at @vidskogs for your contribution. I assume you don’t have permission to merge the pull request and will go ahead and merge it. Can you please double check after I do merge that everything is working properly?

I don't have permission to merge. The boards downloaded and updated correctly and LOS Data works.

**Pull request merged**
