### PR TITLE
Adding DTO Dust button, dust dr in ASLChatter for IFT/TH/MC

### PR DESCRIPTION
**Pull request by mtl1971**

### CODE REVIEW

**Comment by derimmer** [comment]
Hi Morris

I cloned this branch to my machine and built it. No problem there at all. It looks to me like you know a lot more about coding than I do! 

I was able to run the project in my dev environment and to build the VASL module using maven. All good. No errors or surprises.

However, when I open up a game, I cannot figure out how to trigger the dust?

**Comment by derimmer** [comment]
Belay my last message. Just realized where I made an error.

**Comment by derimmer** [comment]
Once I cloned your branch properly it all worked!

The dust button is visible and clear. It doesn't seem to impact any other functionality. In your original message to me you spoke about a dust dr. I could not see any way to trigger that?

**Comment by mtl1971** [comment]
Hi Doug.

Glad to hear it!

It works this way - clicking the 'Dust Level' button cycles through the
levels of dust and back to 'No Dust':

[image: image.png]

If the dust level is not No Dust, when you do an IFT, TH or a MC roll, you
will get a 3rd dr for the dust, and a total with the dust (Be it Light or
Moderate):
[image: image.png]

Cheers,

Morris

**Comment by mtl1971** [comment]
> Hi Morris
> 
> I cloned this branch to my machine and built it. No problem there at all. It looks to me like you know a lot more about coding than I do!
> 
> I was able to run the project in my dev environment and to build the VASL module using maven. All good. No errors or surprises.
> 
> However, when I open up a game, I cannot figure out how to trigger the dust?

Thanks - but, I don't know about that! I'm not sure that my use of the GlobalProperty to handle the dust state is the right way to go about propagating that information, and I think the code I added in ASLDiceBot could be done a bit better, TBH.

**Comment by BigAl737** [comment]
This will be really cool!

**Comment by derimmer** [comment]
> Hi Doug. Glad to hear it! It works this way - clicking the 'Dust Level' button cycles through the levels of dust and back to 'No Dust': image If the dust level is not No Dust, when you do an IFT, TH or a MC roll, you will get a 3rd dr for the dust, and a total with the dust (Be it Light or Moderate): image So the dust roll is automagically added if you are playing with it turned on. Cheers, Morris
> […](#)

You mean it works the way it is supposed to! LOL. 

I must have clicked on every damn DR but those ones. Duh!

So, it all looks good to me and we should build it into 6.6.2. At this stage, I wound normally just proceed with your PR. However, I think Al has submitted some changes today so I would ask if you could ensure that you use the absolute current version of the buildFile then I think we should be ready to go. Once ready, feel free to push your comments to develop without further review. I think the permissions I have given you should let you do that. If not, I will happily do it.

**Comment by derimmer** [comment]
I have cloned a version of develop since the last of today's commits, and was able to build it. I opened a game and all of the recent commits seemed to be in place and working!

Phew! 

Onward to the stars!

**Pull request merged**
