### PR TITLE
Adjust ASLTilingHandler for use with Vassal >= 3.6.17

### PR DESCRIPTION
**Pull request by uckelman**
This PR provides a dramatically simplified ASLTilingHandler, which you can use once Vassal 3.6.17 is released.

Additionally, it updates Maven Wrapper to the current version.

### CODE REVIEW

**Comment by derimmer** [comment]
I will merge this and then pull it into my local development build, which I just moved to 3.6.17. So this will be incorporated into 667 dev and release.

**Comment by derimmer** [comment]
@uckelman  I was able to merge this into my local dev branch. After doing so I get an error in ASLTilingHandler at line 26: @Override. It appears that the method being Override (getImagePaths() does not override a method from the superclass. And my IDE shows that there are no usages of the method. 

If I comment out @Override, then VASL will run but I get funny results. Only some boards will load. Most boards produce a Bad Data in Module: bdXX.gif file not found. I have not found a consistent pattern to this.

**Comment by uckelman** [comment]
It sounds like you're not compiling against Vassal 3.6.17.

**Comment by derimmer** [comment]
Correct. I forgot a setup step in the IDE! Duh!

**Pull request merged**
