### PR TITLE
Adding board h and g for ASLSK

### PR DESCRIPTION
**Pull request by vidskogs**

### CODE REVIEW

**Comment by vidskogs** [comment]
This board does not support VASL LOS yet.

**Comment by zgrose** [comment]
Don't the name in the board versions file and metadata file have to match?

**Comment by derimmer** [comment]
> Don't the name in the board versions file and metadata file have to match?

Yes.

The name attribute in the v5boardVersions.xml file does NOT contain the "bd" prefix. For example. 

boarddata name="iSK" version="6.1" versionDate="2023/11/30" description="" boardType="Starter Kit" publisher="MMP" issued=""

The board name in the BoardMetaData.xml file in the board archive file (the bdXX file) should match. For example:

boardMetadata 
	name="iSK" 
	version="6.1" 
	versionDate="Nov 2023" 
	author="TR" 
	boardImageFileName="bdiSK.gif" 
	hasHills="FALSE" 
	width="33" 
	height="10"
	hexHeight = "64.5"
	hexWidth = "56.25"

Note that as in the example from the BoardMetaData.xml file, the boardImageFileName MUST include the "bd" prefix.

**Comment by geezer09** [comment]
I think everything is in order and the additions are passing my board checking script so i'll merge this pull request to we can test those maps out.

**Pull request merged**
